/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(iqin.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b9cebff3da8376352de823af39defc82)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <vsg60/iqin.h>
// pydoc.h is automatically generated in the build directory
#include <iqin_pydoc.h>

void bind_iqin(py::module& m)
{

    using iqin    = ::gr::vsg60::iqin;


    py::class_<iqin, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<iqin>>(m, "iqin", D(iqin))

        .def(py::init(&iqin::make),
           py::arg("frequency") = 1.0E+9,
           py::arg("level") = -10,
           py::arg("srate") = 5.0E+7,
           py::arg("repeat") = false,
           D(iqin,make)
        )
        




        
        .def("set_frequency",&iqin::set_frequency,       
            py::arg("frequency"),
            D(iqin,set_frequency)
        )


        
        .def("set_level",&iqin::set_level,       
            py::arg("level"),
            D(iqin,set_level)
        )


        
        .def("set_srate",&iqin::set_srate,       
            py::arg("srate"),
            D(iqin,set_srate)
        )


        
        .def("set_repeat",&iqin::set_repeat,       
            py::arg("repeat"),
            D(iqin,set_repeat)
        )

        ;




}








